Repository ToBaeHangOn/Algo_Study, pull requests merged in 2023-03, with the labels that each got.

#64 #14 Junyoung 1/3
  #14 230227/Q1_Boj_분수찾기 2/Solution.kt
  #14 230227/Q2_Boj_최대 점수/Solution.kt
Labels: 리뷰완료_영우, 리뷰완료_석희, 리뷰완료_윤재

#66 Fail : boj_s1_분수찾기 2
  #14 230227/boj_s1_분수찾기 2/Solution.java
  #15 230301/boj_27497_알파벳 블록/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_윤재

#69 #15 Seokhee 1/3
  #15 230301/boj_24432_카드 놀이/Solution.java
Labels: 리뷰완료_준영

#68 #15 Junyoung 2/3
  #15 230301/Q1_Boj_알파벳 블록/Solution.kt
  #15 230301/Q2_Boj_카드 놀이/Solution.kt
  #15 230301/Q3_Boj_핸들 뭘로 하지/Solution.kt
Labels: 리뷰완료_석희

#67 #14 YoonJae 1/3
  #17 230227/Boj_27085 최대 점수/Main.java
  #17 230227/Boj_27437 분수찾기 2/Main.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_석희

#71 #14, #15 Retry Seokhee 4/5
  #14 230227/boj_g2_최대 점수/Solution.java
  #14 230227/boj_s1_분수찾기 2/Solution.java
  #15 230301/boj_24432_카드 놀이/Solution.java
  #15 230301/boj_25498_핸들 뭘로 하지/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_윤재

#70 #14~15 Retry Junyoung
  #14 230227/Q2_Boj_최대 점수/Solution.kt
  #14 230227/Q3_Boj_이 게임에서 진정한 탑은 누구인가/Solution.kt
  #15 230301/Q3_Boj_핸들 뭘로 하지/Solution.kt
Labels: 리뷰완료_석희, 리뷰완료_윤재

#65 # 14 Yeongwoo (0/3)
  230227/problem1.js
  230227/problem2.js
  230227/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_석희, 리뷰완료_윤재

#73 #15 YoonJae 2/3
  #15 230306/Boj_24432 카드 놀이/Main.java
  #15 230306/Boj_25498 핸들 뭘로 하지/Main.java
  #15 230306/Boj_27497 알파벳 블록/Main.java
Labels: 리뷰완료_준영, 리뷰완료_석희

#74 #14 Retry Seokhee
  #14 230227/boj_g1_이 게임에서 진정한 탑은 누구인가/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_윤재

#76 #16 Junyoung 3/3
  #16 230308/Q1_Boj_퇴사/Solution.kt
  #16 230308/Q2_Boj_아기 상어/Solution.kt
  #16 230308/Q3_Boj_낚시왕/Solution.kt
Labels: 리뷰완료_윤재

#77 #16 YoonJae 2/3
  #16 230308/Boj_14501 퇴사/Main.java
  #16 230308/Boj_16236 아기 상어/Main.java
  #16 230308/Boj_17143 낚시왕/Main.java
Labels: 리뷰완료_준영
