Repository ToBaeHangOn/Algo_Study, pull requests merged in 2023-02, with the labels that each got.

#36 #7 Junyoung 3/3
  #7 230130/Q1_Boj_16113_시그널/Solution.kt
  #7 230130/Q2_Boj_1744_수 묶기/Solution.kt
  #7 230130/Q3_Boj_1005_ACM Craft/Solution.kt
Labels: 리뷰완료_석희, 리뷰완료_윤재

#38 #8 Seokhee 3/3
  #8 230201/pro_lv2_무인도 여행/Solution.java
  #8 230201/pro_lv3_등대/Solution.java
  #8 230201/pro_lv3_인사고과/Solution.java
Labels: 리뷰요청_영우, 리뷰완료_준영, 리뷰완료_윤재

#40 #8 Junyoung 1/3
  #8 230201/Q1_Pro_무인도 여행/Solution.kt
  #8 230201/Q2_Pro_인사고과/Solution.kt
  #8 230201/Q3_Pro_등대/Solution.kt
Labels: 리뷰요청_영우, 리뷰완료_석희, 리뷰완료_윤재

#39 #8 YoonJae 2/3
  #8 230201/pro_무인도 여행/Solution.java
  #8 230201/pro_인사고과/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_석희

#41 #7 Retry Seokhee
  #7 230130/Boj_1005_ACM CRAFT/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_윤재

#44 #7, 8 Retry YoonJae 2/2
  #7 230130/Boj_16113 시그널/Main.java
  #8 230201/pro_등대/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_석희

#42 #8 Yeongwoo (3/3)
  230201/problem1.js
  230201/problem2.js
  230201/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_석희, 리뷰완료_윤재

#43 #8 Retry Junyoung
  #8 230201/Q2_Pro_인사고과/Solution.kt
  #8 230201/Q3_Pro_등대/Solution.kt
Labels: 리뷰완료_영우, 리뷰완료_석희, 리뷰완료_윤재

#45 #9 Junyoung 3/3
  #9 230206/Q1_Pro_호텔 대실/Solution.kt
  #9 230206/Q2_Pro_마법의 엘리베이터/Solution.kt
  #9 230206/Q3_Pro_숫자 타자 대회/Solution.kt
Labels: 리뷰요청_영우, 리뷰완료_윤재

#46 #9 Yeongwoo (3/3)
  230206/problem1.js
  230206/problem2.js
  230206/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_윤재

#47 #9 YoonJae 1/3
  #9 230206/pro_마법의 엘리베이터/Solution.java
  #9 230206/pro_호텔 대실/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우

#49 #10 Yeongwoo (3/3)
  230208/problem1.js
  230208/problem2.js
  230208/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_석희, 리뷰완료_윤재

#51 #10 YoonJae 2/3
  #10 230208/pro_뒤에 있는 큰 수 찾기/Solution.java
  #10 230208/pro_시소 짝꿍/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_석희

#48 #10 Junyoung 2/3
  #10 230208/Q1_Pro_뒤에 있는 큰 수 찾기/Solution.kt
  #10 230208/Q2_Pro_시소 짝꿍/Solution.kt
  #10 230208/Q3_Pro_110 옮기기/Solution.kt
Labels: 리뷰완료_영우, 리뷰완료_석희, 리뷰완료_윤재

#50 #9 Seokhee 0/3 / #10 Seokhee 3/3
  #10 230208/pro_level2_뒤에 있는 큰 수 찾기/Solution.java
  #10 230208/pro_level2_시소 짝꿍/Solution.java
  #10 230208/pro_level3_110 옮기기/Solution.java
  #9 230206/pro_level2_숫자 타자 대회/Solution.java
  #9 230206/pro_level2_호텔 대실/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_윤재

#53 #9, 10 Retry YoonJae
  #10 230208/pro_110 옮기기/Solution.java
  #9 230206/pro_마법의 엘리베이터/Solution.java
  #9 230206/pro_숫자 타자 대회/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_석희

#54 #9 Retry Seokhee
  #9 230206/pro_level2_마법의 엘리베이터/Solution.java
  #9 230206/pro_level2_숫자 타자 대회/Solution.java
  #9 230206/pro_level2_호텔 대실/Solution.java
  #9 230206/pro_level3_숫자 타자 대회/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_윤재

#52 #10 Retry Junyoung
  #10 230208/Q3_Pro_110 옮기기/Solution.kt
Labels: 리뷰완료_영우, 리뷰완료_석희, 리뷰완료_윤재

#56 #11 Seokhee 3/3
  #11 230215/pro_level2_귤 고르기/Solution.java
  #11 230215/pro_level3_다단계 칫솔 판매/Solution.java
  #11 230215/pro_level3_부대복귀/Solution.java
Labels: 리뷰완료_준영

#55 #11 Junyoung 3/3
  #11 230215/Q1_Pro_귤 고르기/Solution.kt
  #11 230215/Q2_Pro_다단계 칫솔 판매/Solution.kt
  #11 230215/Q3_Pro_부대복귀/Solution.kt
Labels: 리뷰완료_석희

#58 #12 YoonJae 2/3
  #12 230220/pro_k진수에서 소수 개수 구하기/Solution.java
  #12 230220/pro_억억단을 외우자/Solution.java
  #12 230220/pro_주차 요금 계산/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_석희

#57 #12 Junyoung 3/3
  #12 230220/Q1_Pro_k진수에서 소수 개수 구하기/Solution.kt
  #12 230220/Q2_Pro_주차 요금 계산/Solution.kt
  #12 230220/Q3_Pro_억억단을 외우자/Solution.kt
Labels: 리뷰요청_영우, 리뷰완료_석희, 리뷰완료_윤재

#61 #13 Yeongwoo(2/3)
  230222/problem1.js
  230222/problem2.js
  230222/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_윤재

#62 #12 YoonJae 2/3
  #13 230222/Boj 뱀과 사다리 게임/Main.java
  #13 230222/Boj 파티/Main.java
Labels: 리뷰완료_준영, 리뷰완료_영우

#60 #13 Junyoung 3/3
  #13 230222/Q1_Boj_16928_뱀과 사다리 게임/Solution.kt
  #13 230222/Q2_Boj_1238_파티/Solution.kt
  #13 230222/Q3_Boj_12837_가계부 (Hard)/Solution.kt
Labels: 리뷰완료_영우, 리뷰완료_윤재

#63 #12, 13 Retry YoonJae
  #12 230220/pro_억억단을 외우자/Solution.java
  #13 230222/Boj 가계부(Hard)/Main.java
Labels: 리뷰요청_석희, 리뷰완료_준영, 리뷰완료_영우
