Repository ToBaeHangOn/Algo_Study, pull requests merged in 2023-01, with the labels that each got.

#1 #0 Junyoung 2/3 (sample)
  #0 230102/Boj_10026_적록색약/Solution.kt
  #0 230102/Boj_12015_가장 긴 증가하는 부분 수열 2/Solution.kt
  #0 230102/Boj_18111_마인크래프트/Solution.kt
  .idea/.gitignore
  .idea/ToBaeHangOn_Algo.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
Labels: 리뷰완료_영우, 리뷰완료_석희, 리뷰완료_윤재

#3 230103 test
  #0 230103/Boj_1234 test/Sol.java
Labels: 리뷰요청_영우, 리뷰요청_석희, 리뷰완료_준영

#2 #0 Seokhee 0/0
  testDir/src/Main.java
Labels: 리뷰요청_준영, 리뷰요청_영우, 리뷰요청_윤재

#5 #1 Seokhee 2/3
  #1 230104/Boj_2225_합분해/Solution.java
  #1 230104/Boj_4195_친구네트워트/Solution.java
  #1 230104/Boj_6603_로또/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_윤재

#6 #1 Yoonjae 1/3
  #1 230104/Boj_2225 합분해/Main.java
  #1 230104/Boj_4195 친구 네트워크/Main.java
  #1 230104/Boj_6603 로또/Main.java
Labels: 리뷰완료_준영, 리뷰완료_석희

#4 #1 Junyoung 3/3
  #1 230104/Boj_2225_합분해/Solution.kt
  #1 230104/Boj_4195_친구 네트워크/Solution.kt
  #1 230104/Boj_6603_로또/Solution.kt
  .gitignore
  .idea/.gitignore
  .idea/ToBaeHangOn_Algo.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  .idea/workspace.xml
Labels: 리뷰완료_석희, 리뷰완료_윤재

#8 #1 / retry seokhee
  #1 230104/Boj_4195_친구네트워트/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_윤재

#7 #1 YeongWoo 2/3
  230106/problem1.js
  230106/problem2.js
  230106/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_석희, 리뷰완료_윤재

#9 #1 YoonJae Retry 2/2
  #1 230104/Boj_2225 합분해/Main.java
  #1 230104/Boj_4195 친구 네트워크/Main.java
Labels: 리뷰요청_영우, 리뷰완료_준영, 리뷰완료_석희

#11 #2 Seokhee 2/3
  #2 230109/Pro_베스트앨범/Solution.java
  #2 230109/Pro_퍼즐조각 채우기/Solution.java
  #2 230109/Pro_피로도/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_윤재

#10 #2 YoonJae 2/3
  #2 230109/pro_베스트앨범/Solution.java
  #2 230109/pro_피로도/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_석희

#13 #2 YeongWoo 2/3
  230109/problem1.js
  230109/problem2.js
  230109/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_석희, 리뷰완료_윤재

#12 #2 Junyoung 3/3
  #2 220109/Pro_lv2_피로도/Solution.kt
  #2 220109/Pro_lv3_베스트앨범/Solution.kt
  #2 220109/Pro_lv3_퍼즐 조각 채우기/Solution.kt
Labels: 리뷰완료_영우, 리뷰완료_석희, 리뷰완료_윤재

#17 #3 YeongWoo 3/3
  230111/problem1.js
  230111/problem2.js
  230111/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_석희, 리뷰완료_윤재

#15 #3 Seokhee 1/3
  #3 230111/Pro_가장 먼 노드/Solution.java
  #3 230111/Pro_이모티콘 할인행사/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_윤재

#16 #3 YoonJae 2/3
  #3 230111/Boj_14499 주사위 굴리기/Main.java
  #3 230111/pro_가장 먼 노드/Solution.java
  #3 230111/pro_이모티콘 할인행사/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_석희

#14 #3 Junyoung 2/3
  #2 230109/Pro_lv2_피로도/Solution.kt
  #2 230109/Pro_lv3_베스트앨범/Solution.kt
  #2 230109/Pro_lv3_퍼즐 조각 채우기/Solution.kt
  #3 230111/Boj_14499_주사위 굴리기/Solution.kt
  #3 230111/Pro_lv2_이모티콘 할인행사/Solution.kt
  #3 230111/Pro_lv3_가장 먼 노드/Pro_lv3_가장 먼 노드.kt
Labels: 리뷰완료_영우, 리뷰완료_석희, 리뷰완료_윤재

#19 #3 Retry Seokhee
  #2 230109/Pro_퍼즐조각 채우기/Solution.java
  #2 230109/Pro_퍼즐조각 채우기/Solution_fail.java
  #3 230111/Boj_14499_주사위굴리기/Solution.java
  #3 230111/Pro_이모티콘 할인행사/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_윤재

#18 #3 Retry Junyoung
  #3 230111/Pro_lv2_이모티콘 할인행사/Solution.kt
Labels: 리뷰요청_영우, 리뷰완료_석희, 리뷰완료_윤재

#23 #4 Yeongwoo 2/3
  230111/problem2.js
  230116/problem1.js
  230116/problem2.js
  230116/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_석희, 리뷰완료_윤재

#20 #4 Junyoung 3/3
  #4 230116/1. Boj_s1_1052_물병/Solution.kt
  #4 230116/2. Pro_lv2_메뉴 리뉴얼/Solution.kt
  #4 230116/3. Boj_g3_1493_박스 채우기/Solution.kt
Labels: 리뷰완료_영우, 리뷰완료_석희, 리뷰완료_윤재

#21 #4 Seokhee 2/3
  #4 230116/Boj_1052_물병/Solution.java
  #4 230116/Boj_1493_박스 채우기/Solution.java
  #4 230116/Pro_lv2_메뉴 리뉴얼/Solution.java
  .gitignore
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_윤재

#22 #4 YoonJae 2/3
  #4 230116/Boj_1052 물병/Main.java
  #4 230116/Boj_1493 박스 채우기/Main.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_석희

#24 #5 Junyoung 3/3
  #5 230118/Q1_Boj_1890_점프/Solution.kt
  #5 230118/Q2_Boj_12851_숨바꼭질 2/Solution.kt
  #5 230118/Q3_Boj_1766_문제집/Solution.kt
Labels: 리뷰완료_영우, 리뷰완료_석희, 리뷰완료_윤재

#25 #5 Seokhee 2/3
  #5 230118/Boj_12851_숨바꼭질 2/Solution.java
  #5 230118/Boj_1890_점프/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_윤재

#26 #5 YoonJae 2/3
  #5 230118/Boj_12851 숨바꼭질 2/Main.java
  #5 230118/Boj_1766 문제집/Main.java
  #5 230118/Boj_1890 점프/Main.java
Labels: 리뷰완료_준영, 리뷰완료_영우, 리뷰완료_석희

#32 #6 YoonJae 2/3
  #6 230125/Boj_2644 촌수계산/Main.java
  #6 230125/Boj_3190 뱀/Main.java
Labels: 리뷰완료_준영

#31 #6 Junyoung 2/3
  #6 230125/Q1_Boj_2644_촌수계산/Solution.kt
  #6 230125/Q2_Boj_3190_뱀/Solution.kt
  #6 230125/Q3_Boj_17825_주사위 윷놀이/Solution.kt
Labels: 리뷰완료_윤재

#29 #5 Retry Seokhee
  #4 230116/Boj_1493_박스 채우기/Solution.java
  #5 230118/Boj_1766_문제집/Solution.java
  #6 230125/Boj_2644_촌수계산/Solution.java
Labels: 리뷰요청_영우, 리뷰완료_준영, 리뷰완료_윤재

#33 #6 Retry Junyoung
  #6 230125/Q3_Boj_17825_주사위 윷놀이/Solution.kt
Labels: 리뷰요청_석희, 리뷰완료_윤재

#34 Seokhee
  #6 230125/Boj_17825_주사위/Solution.java
  #6 230125/Boj_3190_뱀/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_윤재

#37 #7 YoonJae 1/3
  #7 230130/Boj_16113 시그널/Main.java
  #7 230130/Boj_1744 수 묶기/Main.java
Labels: 리뷰완료_준영, 리뷰완료_석희

#35 #7 Seokhee 2/3
  #7 230130/Boj_16113_시그널/Solution.java
  #7 230130/Boj_1744_수묶기/Solution.java
Labels: 리뷰완료_준영, 리뷰완료_윤재

#28 #5 Yeongwoo 1/3
  230118/problem1.js
  230118/problem2.js
  230118/problem3.js
Labels: 리뷰완료_준영, 리뷰완료_석희, 리뷰완료_윤재
